 cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: false
      routes:
        - id: Clinic-Service
          uri: http://localhost:8091
          predicates:
            - Path=/clinic/**
        - id: Auth-Service
          uri: http://localhost:8094
          predicates:
            - Path=/auth/**
        - id: Patient-Service
          uri: http://localhost:8092
          predicates:
            - Path=/patient/**
        - id: Notification-Service
          uri: http://localhost:8093
          predicates:
            - Path=/notification/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowed-headers: '*'
            allowedMethods: GET, POST, PUT, DELETE
            max-age: '3600'
            allowed-origins: '*'

server:
  port: 8090

---
spring:
  config:
    activate:
      on-profile: prod

  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: false
      routes:
        - id: Clinic-Service
          uri: http://localhost:8091
          predicates:
            - Path=/clinic/**
        - id: Patient-Service
          uri: http://localhost:8092
          predicates:
            - Path=/patient/**
        - id: Notification-Service
          uri: http://localhost:8093
          predicates:
            - Path=/notification/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowed-headers: '*'
            allowedMethods: GET, POST, PUT, DELETE
            max-age: '3600'
            allowed-origins: '*'
