# 🏥 Clinic Service Config
spring:
  config:
    activate:
      on-profile: clinic-dev
  application:
    name: clinic-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/abms_local_dev

server:
  port: 8091
  servlet:
    context-path: /clinic

interfaceId: com-abms-clinic   # <- Added this
custom:
  interfaceId: com-abms-clinic
