spring:
  config:
    activate:
      on-profile: notification-dev
  application:
    name: notification
  server:
    port: 8093
    servlet:
      context-path: /notification

custom:
  interfaceId: abms-notification
